spring:
  datasource:
    url: "jdbc:h2:mem:"
    username: login
    password: password
    schema:
      - sql/createAuthor.sql
      - sql/createGenre.sql
      - sql/createBook.sql
      - sql/createAuthorAndBook.sql
      - sql/testData.sql
  shell:
    interactive:
      enabled: true

logging.level.org.springframework.jdbc.core.JdbcTemplate: DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils: TRACE

