INSERT INTO TABLE_AUTHOR(AUTHORNAME) VALUES ('Рэй Брэдбери');
INSERT INTO TABLE_AUTHOR(AUTHORNAME) VALUES ('Федор Достоевский');
INSERT INTO TABLE_AUTHOR(AUTHORNAME) VALUES ('Иван Шмелев');
INSERT INTO TABLE_AUTHOR(AUTHORNAME) VALUES ('Гилберт Честертон');

INSERT INTO TABLE_GENRE(GENRENAME) VALUES ('Научная фантастика');
INSERT INTO TABLE_GENRE(GENRENAME) VALUES ('Роман');
INSERT INTO TABLE_GENRE(GENRENAME) VALUES ('Философия');
INSERT INTO TABLE_GENRE(GENRENAME) VALUES ('Классическая проза');

INSERT INTO TABLE_BOOK(BOOKNAME, AUTHORID, GENREID) VALUES (
    '451 градус по фаренгейту',
    (SELECT AUTHORID FROM TABLE_AUTHOR WHERE AUTHORNAME = 'Рэй Брэдбери'),
    (SELECT GENREID FROM TABLE_GENRE WHERE GENRENAME = 'Научная фантастика')
);
INSERT INTO TABLE_BOOK(BOOKNAME, AUTHORID, GENREID) VALUES (
    'Преступление и наказание',
    (SELECT AUTHORID FROM TABLE_AUTHOR WHERE AUTHORNAME = 'Федор Достоевский'),
    (SELECT GENREID FROM TABLE_GENRE WHERE GENRENAME = 'Роман')
);
INSERT INTO TABLE_BOOK(BOOKNAME, AUTHORID, GENREID) VALUES (
    'Лето Господне',
    (SELECT AUTHORID FROM TABLE_AUTHOR WHERE AUTHORNAME = 'Иван Шмелев'),
    (SELECT GENREID FROM TABLE_GENRE WHERE GENRENAME = 'Роман')
);
INSERT INTO TABLE_BOOK(BOOKNAME, AUTHORID, GENREID) VALUES (
    'Ортодоксия',
    (SELECT AUTHORID FROM TABLE_AUTHOR WHERE AUTHORNAME = 'Гилберт Честертон'),
    (SELECT GENREID FROM TABLE_GENRE WHERE GENRENAME = 'Философия')
);
INSERT INTO TABLE_BOOK(BOOKNAME, AUTHORID, GENREID) VALUES (
    'Дневник писателя',
    (SELECT AUTHORID FROM TABLE_AUTHOR WHERE AUTHORNAME = 'Федор Достоевский'),
    (SELECT GENREID FROM TABLE_GENRE WHERE GENRENAME = 'Классическая проза')
);

INSERT INTO TABLE_COMMENT(BOOKID, COMMENT) VALUES (
    1,
    '451 градус по фаренгейту, Рэй Брэдбери'
);

INSERT INTO TABLE_COMMENT(BOOKID, COMMENT) VALUES (
    2,
    'Преступление и наказание, Федор Достоевский'
);

INSERT INTO TABLE_COMMENT(BOOKID, COMMENT) VALUES (
    3,
    'Лето Господне, Иван Шмелев'
);

INSERT INTO TABLE_COMMENT(BOOKID, COMMENT) VALUES (
    3,
    'Лето Господне, Иван Шмелев, автобиографический роман'
);

INSERT INTO TABLE_COMMENT(BOOKID, COMMENT) VALUES (
    4,
    'Ортодоксия, Гилберт Честертон'
);

INSERT INTO TABLE_COMMENT(BOOKID, COMMENT) VALUES (
    5,
    'Дневник писателя, Федор Достоевский'
);