DROP TABLE IF EXISTS TABLE_BOOK;
DROP TABLE IF EXISTS TABLE_AUTHOR;
DROP TABLE IF EXISTS TABLE_GENRE;
DROP INDEX IF EXISTS TABLE_BOOK_K01;
DROP INDEX IF EXISTS TABLE_AUTHOR_K01;
DROP INDEX IF EXISTS TABLE_GENRE_K01;

CREATE TABLE TABLE_AUTHOR(
    AUTHORID SERIAL PRIMARY KEY,
    AUTHORNAME VARCHAR(1024) NOT NULL UNIQUE
);
CREATE INDEX TABLE_AUTHOR_K01 ON TABLE_AUTHOR(UPPER(AUTHORNAME));

CREATE TABLE TABLE_GENRE(
    GENREID SERIAL PRIMARY KEY,
    GENRENAME VARCHAR(255) NOT NULL UNIQUE
);
CREATE INDEX TABLE_GENRE_K01 ON TABLE_GENRE(UPPER(GENRENAME));

CREATE TABLE TABLE_BOOK(
    BOOKID SERIAL PRIMARY KEY,
    BOOKNAME VARCHAR(1024) NOT NULL,
    AUTHORID INTEGER NOT NULL,
    GENREID INTEGER NOT NULL,
    CONSTRAINT TABLE_BOOK_FK01 FOREIGN KEY (AUTHORID) REFERENCES TABLE_AUTHOR (AUTHORID) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT TABLE_BOOK_FK02 FOREIGN KEY (GENREID) REFERENCES TABLE_GENRE (GENREID) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX TABLE_BOOK_K01 ON TABLE_BOOK(UPPER(BOOKNAME));